### ISSUE TITLE
'noupdate' argument not working

### ISSUE THREAD

**Issue by Hakim3i** [lulzsun/blitz-app-adblock#1]

**Comment by lulzsun** [comment]
Still works for me on Blitz 1.12.13, although I did a clean reinstall. Could you provide more information as to why its not working? (blank screen, not launching, not blocking ads, etc.)

**Comment by Hakim3i** [comment]
when I patch it blitz won't open 
![image](https://user-images.githubusercontent.com/11870227/93128765-e76fa580-f6c7-11ea-8450-8f811019f673.png)
[app.log](https://github.com/lulzsun/blitz-app-adblock/files/5220521/app.log)

**Comment by Hakim3i** [comment]
I updated my java jre and it is working now on 1.12.14 thank you for the program.

**Comment by lulzsun** [comment]
Thanks for that, I will take a look into it and fix it.

**Comment by Hakim3i** [comment]
Thank to you for this.

**Comment by Bemirror99** [comment]
first, thanks for your code.

it doesn't work since this update...

**Comment by lulzsun** [comment]
This has been fixed in the latest release.
