### ISSUE TITLE
MacOS version

### ISSUE THREAD

**Issue by BenDaSpur** [lulzsun/blitz-app-adblock#10]
Would be great to have a MacOS version available. The application itself looks like it has the same file setup. For most people the app is located at /Applications/Blitz.app/Contents

Anyways, thanks for the great app, I have it on my windows computer 💯

**Comment by lulzsun** [comment]
It is very possible, the patcher can be ported over to .NET Core for cross platform compatibility. 

However I currently do not have a MacOS computer so I wouldn't be able to get that done any time soon. Maybe someone else could give it a try.

**Comment by lulzsun** [comment]
I am actually in the process of rewriting the patcher in Node.js which will make it cross-platform.

If you could provide the full file location of app.asar, I could probably get it to work on MacOS.

**Comment by jenny-chen** [comment]
Full path on Mac appears to be: /Applications/Blitz.app/Contents/Resources/app.asar

**Comment by lulzsun** [comment]
I have just [released](https://github.com/lulzsun/blitz-app-adblock/releases/tag/3.0.0) the Node.js patcher, allowing it to theoretically work on MacOS. 

You can also compile and debug it for yourself using npm and Node.

Let me know if it works out.

**Comment by jenny-chen** [comment]
It doesn't seem like it's working. I'm running into errors both running the macOS patcher and also trying to compile it myself. I'm not too familiar with these packages, is something wrong on my end?

Running .out file
![image](https://user-images.githubusercontent.com/9325919/104781913-5978f980-5751-11eb-8179-51558b74443d.png)

Compiling myself
![image](https://user-images.githubusercontent.com/9325919/104780922-8e844c80-574f-11eb-8735-ea41d115afa2.png)

**Comment by lulzsun** [comment]
Have you tried `npm run start` and see if that does anything? If that works then must be something related to the pkg module.

**Comment by jenny-chen** [comment]
`npm run start` returns an error as well 

![image](https://user-images.githubusercontent.com/9325919/104783138-68f94200-5753-11eb-8461-576fd5eb0997.png)

**Comment by lulzsun** [comment]
I think line 11 of blitz-app-adblock.js is creating the error. 
I believe in the first argument of path.join(), `process.env.APPDATA` is undefined on macOS. Try initializing appPath to be an empty string and see if that does it.

**Comment by jenny-chen** [comment]
That fixed part of the issue. Another issue was that unix systems use forward slashes in file paths while windows uses backslashes so it wasn't finding the right file. Changing it to the code below helped it find `app.asar` but now I get:
![image](https://user-images.githubusercontent.com/9325919/104784392-2be27f00-5756-11eb-8f41-f5046aeebc15.png)

```javascript
        // mac os app path
        if (process.platform === "darwin") {
            appPath = '/Applications/Blitz.app/Contents/Resources';
        }

        if(!fs.existsSync(`${appPath}/app.asar`)) {
            console.log("app.asar not found!");
        }
        else {
            console.log('Extracting app.asar...');
            await asar.extractAll(`${appPath}/app.asar`, `${appPath}/app/`);
```

**Comment by jenny-chen** [comment]
Also I'll note that this slash issue also applies to the `npm run build` issue. Changing `.\build\` to `./build/` causes this instead:
![image](https://user-images.githubusercontent.com/9325919/104785383-5fbea400-5758-11eb-8c8b-b79fb83b1956.png)

**Comment by lulzsun** [comment]
What node version are you using? It might only be working on my old node 10.16.3. I'll try updating in a bit and seeing if the same problem occurs.

**Comment by lulzsun** [comment]
It appears that node 15 is not supported by pkg. I think I'll update to node 14.15.4 (latest LTS version) and see if that works.

**Comment by lulzsun** [comment]
Try pulling the latest changes and use node 14.15.4 to compile. I also re-uploaded the 3.0.0 release with all the changes if you want to test that first.

**Comment by jenny-chen** [comment]
I tried the new 3.0.0 release and it seems to work! Cheers, thanks for helping :D

**Comment by lulzsun** [comment]
No problem, and thank you for helping me debug all this to work on macOS. Cheers!
