### ISSUE TITLE
Error with noupdate

### ISSUE THREAD

**Issue by Sato-Isolated** [lulzsun/blitz-app-adblock#11]
![image](https://user-images.githubusercontent.com/12450341/100013169-b05af600-2dd4-11eb-9599-8f8502606f53.png)

update : 1.13.41

**Comment by lulzsun** [comment]
Still working from a fresh reinstall. Are you using the optional arguments? That may be the issue if you didn't do a clean reinstall before applying the adblock. The update might have broken the patching for those features.

**Comment by freefrank** [comment]
same here. noupdate argument break the app.

**Comment by lulzsun** [comment]
Oh sorry, I misread the title. Yeah it looks like noupdate argument is broken. I'll take a look at it when I got the time.

**Comment by lulzsun** [comment]
Should now be fixed in 2.0.4.
