### ISSUE TITLE
New update = impossible to start Blitz again

### ISSUE THREAD

**Issue by Malix-Off** [lulzsun/blitz-app-adblock#15]
While a new update is available, it is impossible to start Blitz again, and your program close before i can type the -noupdate command.

**Comment by lulzsun** [comment]
You must uninstall blitz and reinstall it fresh whenever there is a new update.

You must use the -noupdate command as a launch argument. You don't type it in the console window.

**Comment by Malix-Off** [comment]
> You must use the -noupdate command as a launch argument. You don't type it in the console window.

Where to input this command ?

**Comment by lulzsun** [comment]
[This is one way of running the program with an argument.](https://github.com/lulzsun/blitz-app-adblock/issues/12#issuecomment-733463442)

**Comment by Malix-Off** [comment]
Thanks ! thank you for your great work ;)
