### ISSUE TITLE
Bootloop blitz instead of update

### ISSUE THREAD

**Issue by loveuseless** [lulzsun/blitz-app-adblock#18]
Reinstall helped. ¯\_(ツ)_/¯

**Comment by lulzsun** [comment]
This is normal behavior. Anytime there is an update, with the adblock patch, it will cause issues.

I might design a workaround to this issue in the future, don't know when exactly.

**Comment by loveuseless** [comment]
it would me very nice

**Comment by O11Software** [comment]
Yeah, this still exists :)

**Comment by lulzsun** [comment]
I'll have to find a creative way to have the adblock patch reinstall itself or find some other workaround. I'll give it a shot some time later this week.

**Comment by lulzsun** [comment]
I have just [released 3.0.0](https://github.com/lulzsun/blitz-app-adblock/releases/tag/3.0.0) that covers this problem.

Blitz will now properly uninstall itself, uninstall the patch, and install the update without causing a boot-loop issue anymore.

**Comment by loveuseless** [comment]
> I have just [released 3.0.0](https://github.com/lulzsun/blitz-app-adblock/releases/tag/3.0.0) that covers this problem.
> 
> Blitz will now properly uninstall itself, uninstall the patch, and install the update without causing a boot-loop issue anymore.
man, you're awesome
