### ISSUE TITLE
You got anything against that annoying popup ?

### ISSUE THREAD

**Issue by paakjis** [lulzsun/blitz-app-adblock#19]
Hey, nice patch.
Blitz app keeps poping up, you got anything against that ?

**Comment by lulzsun** [comment]
Do you mean after a League Of Legends game, it pops up to front? I don't use Blitz often, so I'm not exactly sure what you mean.

**Comment by paakjis** [comment]
Yeah, it pops up automatically after the game. And when you have to accept game.
A lot of times when I'm about to press Accept, blitz pops up and I click on Decline in blitz , its just a shit feature for users to look at more ads. And useful to none if I have no ads to start with.
My fix to this problem is to move it to "Desktop 2".

**Comment by lulzsun** [comment]
I'll try to take a look at this sometime later this month.

**Comment by mtaki14** [comment]
There's a setting to disable the accept popup in blitz  itself

**Comment by lulzsun** [comment]
> 
> 
> There's a setting to disable the accept popup in blitz itself

I've noticed that as well, must have been a recently added feature. Closing this issue for now.
