### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by Adogx** [lulzsun/blitz-app-adblock#20]
it will go to 'Downloading ad & tracking filters...' and then not respond. I cannot close it, I have to restart my pc to close it.

**Comment by ColossalCalamari** [comment]
There was an update to Blitz app. I believe in cases like these it's recommended to 1) uninstall Blitz 2) reinstall Blitz 3) re-run the adblock. That seemed to work for me, no crashes or anything so far, but haven't played a League game yet.

**Comment by lulzsun** [comment]
Yeah this is normal behavior for now until a workaround can be found to have the adblock patch reapply itself.

Duplicate issue of #18.

**Comment by Adogx** [comment]
I did reinstall blitz, because it wouldn't open, and it's only after this that the patch will crash
