### ISSUE TITLE
Unpatch Functionality

### ISSUE THREAD

**Issue by avarun42** [lulzsun/blitz-app-adblock#21]
Is it possible to update this in order to add unpatch functionality? That way we can simply unpatch, update Blitz, then patch again, instead of having to clean install Blitz every time an update comes out. Thanks for your work on this btw!

**Comment by lulzsun** [comment]
I am currently working on a way for the patch to reapply itself when Blitz automatically updates. If I can't get it to work the way I want it to, then I might consider adding this functionality in.

**Comment by lulzsun** [comment]
I have just [released 3.0.0](https://github.com/lulzsun/blitz-app-adblock/releases/tag/3.0.0) that covers this problem. 

Blitz will now properly uninstall itself and the patch so a bootloop will not occur anymore.
