### ISSUE TITLE
The -noupdate Option is Not Working

### ISSUE THREAD

**Issue by Radizzt** [lulzsun/blitz-app-adblock#26]
I installed the program with the `-noupdate` option, but Blitz app still continues to update and triggering an infinite loop of updating the app.

Maybe I didn't do the option correctly (cmd into the directory and ran `blitz-app-adblock-win.exe -noupdate`)?

**Comment by lulzsun** [comment]
The script relating to noupdate must be broken on latest version of Blitz. I'll look into it.

**Comment by lulzsun** [comment]
I've updated the line to patch for this option, I haven't tested it but I'm just assuming it will work. Closing this issue.
