### ISSUE TITLE
i got this error

### ISSUE THREAD

**Issue by Sato-Isolated** [lulzsun/blitz-app-adblock#27]
> C:\Users\Edenl>C:\Users\Edenl\Desktop\blitz-app-adblock\blitz-app-adblock-win.exe -noupdate
> Extracting app.asar...
> Downloading ad & tracking filters...
> Patching...
> Error: ENOENT: no such file or directory, copyfile './build/adblocker.umd.min.js' -> 'C:\Users\Edenl\AppData\Local\Programs\Blitz\resources/app/src/adblocker.umd.min.js'
>     at Object.copyFileSync (fs.js:1912:3)
>     at Object.copyFile (F:\snapshot\blitz-app-adblock\io.js)
>     at start (F:\snapshot\blitz-app-adblock\blitz-app-adblock.js)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
>   errno: -4058,
>   syscall: 'copyfile',
>   code: 'ENOENT',
>   path: './build/adblocker.umd.min.js',
>   dest: 'C:\\Users\\Edenl\\AppData\\Local\\Programs\\Blitz\\resources/app/src/adblocker.umd.min.js'
> }
> 
> Press ENTER to quit...

Blitz update : 1.13.77

**Comment by lulzsun** [comment]
Is 'adblocker.umd.min.js' file in the same directory as the patcher?

**Comment by Sato-Isolated** [comment]
yes

**Comment by Sato-Isolated** [comment]
oh sorry i just forgot to run as admin ^^
