### ISSUE TITLE
The latest version doesn't work for me

### ISSUE THREAD

**Issue by asd987467104** [lulzsun/blitz-app-adblock#28]
The latest version doesn't work,it still has ads.

The old version is still working.

Thank you for your work!

**Comment by lulzsun** [comment]
Still working for me and most others. Are you running it as admin?

If there are any errors displayed in the console, that would also be helpful for figuring out the issue.

**Comment by asd987467104** [comment]
Yes, I'm running as an administrator
![1](https://user-images.githubusercontent.com/47688219/106374294-d98f9800-63bc-11eb-9b85-ffeb27fb7835.PNG)

**Comment by lulzsun** [comment]
It looks like you can't establish a connection to some Github URLs to download some ad filters.

These are the two filters that are downloaded from Github when installing the patch:
```
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt
```

If you can access them fine through a web browser, then maybe a firewall is preventing the patcher from accessing these URLs?

**Comment by asd987467104** [comment]
Web browsing is fast
I tried to turn off the firewall
Exclude items and turn off antivirus
It's still not working
Sometimes the patcher won't download
sad
![2](https://user-images.githubusercontent.com/47688219/106379114-b4168480-63e4-11eb-9b7e-97b599d04fbf.PNG)

**Comment by lulzsun** [comment]
Closing this issue since it is old and user specific issue.
