### ISSUE TITLE
an error occured

### ISSUE THREAD

**Issue by Bemirror99** [lulzsun/blitz-app-adblock#3]
First, Thank you for your efforts!

After this patch, an error has occurred.

I ran the adblock program as usual when I had seen the blitz app showing new version patch and not running.

Then I ran the blitz app and this message popped up...

![image](https://user-images.githubusercontent.com/59559008/96307914-53358d00-103d-11eb-9229-b496f666718d.png)

**Comment by lulzsun** [comment]
Fixed in the latest release version. You can download it [here](https://github.com/lulzsun/blitz-app-adblock/releases/tag/2.0.3).
