### ISSUE TITLE
3rd of Feb 2021 blitz update stopped the adblock from working.

### ISSUE THREAD

**Issue by Cyinthia** [lulzsun/blitz-app-adblock#30]
```
Extracting app.asar...
Downloading ad & tracking filters...
Patching...
C:\Users\User folder\AppData\Local\Programs\Blitz\resources/app/src/createWindow.js => Writing to line 119: try {const fs = require('fs');const { FiltersEngine, Request } = require('./adblocker.umd.min.js');const filters =fs.readFileSync(require.resolve('./easylist.txt'), 'utf-8') + '\n' +fs.readFileSync(require.resolve('./easyprivacy.txt'), 'utf-8') + '\n' +fs.readFileSync(require.resolve('./ublock-ads.txt'), 'utf-8') + '\n' +fs.readFileSync(require.resolve('./ublock-privacy.txt'), 'utf-8') + '\n' +fs.readFileSync(require.resolve('./peter-lowe-list.txt'), 'utf-8') + '\ngoogleoptimize.com\n';const engine = FiltersEngine.parse(filters);windowInstance.webContents.session.webRequest.onBeforeRequest({ urls: ['*://*/*'] }, (details, callback) => {const {match} = engine.match(Request.fromRawDetails({ url: details.url }));if (match == true) {log.info('BLOCKED:', details.url);callback({cancel: true});} else {callback({cancel: false});}});} catch (error) {log.error(error);}
C:\Users\User folder\AppData\Local\Programs\Blitz\resources/app/src/createWindow.js => Writing to line 106: session: true,
Repacking app.asar...
[Error: UNKNOWN: unknown error, open 'C:\Users\User folder\\AppData\Local\Programs\Blitz\resources\app.asar'] {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'open',
  path: 'C:\\Users\\User folder\\\AppData\\Local\\Programs\\Blitz\\resources\\app.asar'
```
Hasn't been working since the blitz update on the 3rd of February, replaced my user folder name with "User folder". Redownloaded adblock again to be sure as well.

**Comment by lulzsun** [comment]
Still working on latest version of Blitz and the adblocker.

I think you might have Blitz open while installing the adblocker. You must make sure Blitz isn't running in the background while running the adblock patcher.

**Comment by Cyinthia** [comment]
> Still working on latest version of Blitz and the adblocker.
> 
> I think you might have Blitz open while installing the adblocker. You must make sure Blitz isn't running in the background while running the adblock patcher.

Ahh I see, in the previous version it worked even with it on so I didn't think about that.

**Comment by lulzsun** [comment]
Yeah, the latest version uses a new method to extract, patch, and zip back up the files. In which it requires Blitz to be closed.

Before, it wouldn't zip back up the files. This would allow you to have Blitz open, but also would cause the 'boot-loop-on-update' issue if the files weren't zipped up when an update occurred.

So that is why it is now required to have Blitz closed in order to patch files. Hope that provides some interesting insight on how things work.
