### ISSUE TITLE
error running

### ISSUE THREAD

**Issue by narcoticcoin** [lulzsun/blitz-app-adblock#31]
[app.log](https://github.com/lulzsun/blitz-app-adblock/files/5928899/app.log)
get this everytime i try to run the program

**Comment by lulzsun** [comment]
These logs aren't providing enough information for me to help you. Can you provide any pictures of error popups?

**Comment by narcoticcoin** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/78569664/106973661-ea237380-6718-11eb-9cda-cd72f9742b53.png)
this is what the launcher shows

**Comment by lulzsun** [comment]
You need to have Blitz.gg closed before running the patcher now. Duplicate issue #30.
