### ISSUE TITLE
-noupdate argument not working

### ISSUE THREAD

**Issue by MgDark** [lulzsun/blitz-app-adblock#32]
![Capture](https://user-images.githubusercontent.com/16635724/106991168-12789580-674c-11eb-9220-c90f62323615.JPG)
Blitz was working normally, noticed the new release, installed the patch and now Blitz doesn't want to open.
Is pretty likely something broke, considering they are doing quite a few changes to builds.
Edit: Oh yeah used -noupdate option, thats probably the problem?

**Comment by lulzsun** [comment]
Yeah, -noupdate is currently broken. Avoid using it for now.
