### ISSUE TITLE
You guys are awesome TY!!! 

### ISSUE THREAD

**Issue by xTalented** [lulzsun/blitz-app-adblock#35]
I'd like to buy you guys a coffee or something, do you have donation link?

**Comment by lulzsun** [comment]
Hey thanks!

I am currently the only person that is actively maintaining this repo. You can donate using [this PayPal.me link](paypal.me/jminquach). 

Appreciate the support. 🎉

**Comment by xTalented** [comment]
sent, keep up the good work!

**Comment by lulzsun** [comment]
Thanks again!
