### ISSUE TITLE
doesnt patch 2021-03-05

### ISSUE THREAD

**Issue by Claud1995** [lulzsun/blitz-app-adblock#37]
Error: Current Blitz version caused patch comparison check to fail. Look for a new patcher release or create a new issue on Github!

    at Object.modifyFileAtLine (F:\snapshot\blitz-app-adblock\io.js)
    at start (F:\snapshot\blitz-app-adblock\blitz-app-adblock.js)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by lulzsun** [comment]
Have you downloaded the latest release? I don't seem to be having this problem on the current update of Blitz (1.13.135).

**Comment by Claud1995** [comment]
I did

**Comment by lulzsun** [comment]
Are you on release 3.0.3?

**Comment by Claud1995** [comment]
I updated everything after Blitz got stuck in infinite updating loop

reinstalled Blitz and then tried patching the adblock, didn't work so I
went and downloaded latest thinking that might help, it didn't

**Comment by jarjumarvin** [comment]
The currently newest release of Blitz is 1.13.136 as of writing this comment.

**Comment by lulzsun** [comment]
Looks like the patcher is working on 1.13.136 on my end. Are you still having issues?

**Comment by Claud1995** [comment]
redownloaded and reinstalled both Blitz and the adblocker just now, same
issue added the screenshot

2021-03-06, št, 15:06 lulzsun <notifications@github.com> rašė:

**Comment by fmohican** [comment]
Its working, just remember to apply patch via "Run As Administrator".

**Comment by majorcyto** [comment]
I had a similar issue with todays update, but running the patch tool as Administrator did the trick. Thanks!

**Comment by lulzsun** [comment]
Seems like that may be the solution, I'll make a note of that on README and release notes.

Closing this.
