### ISSUE TITLE
New Mac Blitz version 1.13.138.1482

### ISSUE THREAD

**Issue by adhsu** [lulzsun/blitz-app-adblock#38]
Patch fails: `Error: Current Blitz version caused patch comparison check to fail. Look for a new patcher release or create a new issue on Github!`

**Comment by lulzsun** [comment]
Still working on Windows for me, I can't see why there's an issue on Mac version. Have you tried reinstalling Blitz?

**Comment by Rae-Gun** [comment]
I was having issues with the adblocker not working on Windows, however found out that I need to force quit blitz from task manager first, then run the script. Apparently having blitz opened while running the script doesn't work (the script force closes blitz, but it doesn't continue running the script afterwards on my end).

**Comment by lulzsun** [comment]
Closing this issue. Move any replies to the new issue #41.
