### ISSUE TITLE
No instructions on how to install for iOS

### ISSUE THREAD

**Issue by eduardrudko** [lulzsun/blitz-app-adblock#39]
First of all thanks for the efforts, this ad is really annoying. Back to the problem, could you please add instructions on how to install the solution for iOS, would be much appreciated, thanks.

**Comment by lulzsun** [comment]
I don't know the exact procedure on how to run the binary for macOS since I don't have a computer with it, but I'm assuming you run it through terminal. Hopefully someone else can provide you a more in-depth answer.

**Comment by eduardrudko** [comment]
Alright, so its pretty straightforward.

this is the output i've got: 
`lilkunien@working-station blitz-app-adblock % ./blitz-app-adblock-macos         
Checking for Blitz...
app.asar not found!

Press ENTER to quit...
lilkunien@working-station blitz-app-adblock % `

The problem is that my blitz app is not located on a root level but on the user level.
`~/Applications/Blitz.app`

I think we need to check user level app dir as well as a fall back. I don't think ppl tend to install their apps in other different dirs than `/Applications` and `~/Applications`

I would really appreciate your efforts if you could do it in a free time, should be real quick. Thank you!

**Comment by newaroundhere** [comment]
Hi,

This is my first post on GitHub so I apologize if I'm breaking a rule by posting my question here.  I'm really new to using Terminal on my Mac and new to coding in general.  How do I run this patch to get rid of ads.  I tried going into Terminal and doing what you said but keep getting permission denied.  I also tried using sudo su with no avail.  Is there a location I need to save the folder or file?  I tried on my desktop but that didn't work either.  Sorry I'm such a newb but help would be appreciated.

**Comment by lulzsun** [comment]
> 
> 
> #40

@eduardrudko I have compiled a [prerelease](https://github.com/lulzsun/blitz-app-adblock/releases/tag/3.0.4) with your pull request if you'd like to try it out.

**Comment by eduardrudko** [comment]
@newaroundhere do this:
`cd <dir_where_binary_is>`
`chdome +x blitz_app_adblock_mac`
`./blitz_app_adblock_mac`

**Comment by eduardrudko** [comment]
@lulzsun thanks, i did check it. It turned out to be Node js does not support tilde references as explained here: https://github.com/nodejs/node/issues/684
i've made a small fix for it.

**Comment by lulzsun** [comment]
Sounds great! Thanks for the work. Closing this issue.
