### ISSUE TITLE
I have some troubles

### ISSUE THREAD

**Issue by erickafe** [lulzsun/blitz-app-adblock#4]
[app.log](https://github.com/lulzsun/blitz-app-adblock/files/5394574/app.log)
![image](https://user-images.githubusercontent.com/35701053/96319779-3fa30b80-0fd6-11eb-8abc-5e18c0c834dd.png)

**Comment by lulzsun** [comment]
Fixed in the latest release version. You can download it [here](https://github.com/lulzsun/blitz-app-adblock/releases/tag/2.0.3).
