### ISSUE TITLE
Not working on latest Blitz version

### ISSUE THREAD

**Issue by majorcyto** [lulzsun/blitz-app-adblock#43]
Even when running as admin, it is no longer blocking on the latest version. when it is on the ad tracker and filter step it has a connection time out and does not continue.

**Comment by lulzsun** [comment]
Still working on my end, do you have any firewalls that may be blocking the application from downloading ad tracker/filter lists?

**Comment by majorcyto** [comment]
So I have no clue why, but suddenly it works again and I no longer get the connection time out error I originally mentioned. 🤔Blitz just seems to have a lot of service issues in general now and days for whatever reason.
