### ISSUE TITLE
It sends me an error when patching

### ISSUE THREAD

**Issue by erickafe** [lulzsun/blitz-app-adblock#49]
![image](https://user-images.githubusercontent.com/35701053/119073864-9c730400-b9b3-11eb-9112-3e8d8cb71fea.png)

**Comment by andranoxi** [comment]
dupe of #45 

https://github.com/lulzsun/blitz-app-adblock/issues/45#issuecomment-844192270

**Comment by lulzsun** [comment]
See #45 for more details
