### ISSUE TITLE
How to Remove

### ISSUE THREAD

**Issue by HSHABx99** [lulzsun/blitz-app-adblock#5]
there is no way to remove the app in the readme , i'd like to remove it as as it breaks Porofessor aswell

**Comment by lulzsun** [comment]
You can remove it by reinstalling Blitz. I will update the Readme about this.

**Comment by EdwardDillinger** [comment]
That is not working for me for some reason. I downloaded the newest version of blitz and when I click to install it just goes into an installation loop where it starts applying the updates then crashes the game. I have deleted the files that I downloaded from this project and emptied trash, but this is still happening.

**Comment by lulzsun** [comment]
Then I am not sure what the problem is. If you look at the source code, the adblock patcher only modifies the files located in app.asar. Doesn't modify anything else afterwards. Are you sure there isn't another program that might be affecting it?

**Comment by EdwardDillinger** [comment]
Downloaded the ZIP again and ran the adblock application one more time and did the fresh re-install and now it is opening. *shrugs* thanks for this product and for being responsive! Will continue to use for sure.

**Comment by lulzsun** [comment]
Glad to see you got it working. 🥳
