### ISSUE TITLE
won't run with administrator & without, following issue ; 

### ISSUE THREAD

**Issue by Liveyss** [lulzsun/blitz-app-adblock#50]
![blitz-app-adblock-win_vCq56ohIjP](https://user-images.githubusercontent.com/70145454/119240038-8a2ccd80-bb4d-11eb-912d-c756832400ad.png)

**Comment by Liveyss** [comment]
hello?

**Comment by mSv1306** [comment]
Could you solve it?

**Comment by Liveyss** [comment]
> Could you solve it?

nope

**Comment by Liveyss** [comment]
> Could you solve it?

Use op.gg desktop app, does everything blitz does but better and you don't have to rely on these devs to NOT fix their issue.  http://op.gg/desktop/?utm_source=opgg&utm_medium=banner&utm_campaign=deskkor1

**Comment by lulzsun** [comment]
Sorry that I was unable to help you fix your issue, I've been busy lately and this Blitz adblocker project is low priority for me.

I was going to look into your issue eventually, but it appears you have found alternative solution. 

Just so you know, I'm not really obligated to fix anything if the adblocker doesn't work. I don't get paid for this. 

Thanks for the kind email you sent me though, I hope you find peace in your life.

**Comment by Liveyss** [comment]
get cancer
