### ISSUE TITLE
Latest Blitz breaks patching

### ISSUE THREAD

**Issue by boyd-it** [lulzsun/blitz-app-adblock#51]
Checking for Blitz...
Extracting app.asar...
Downloading ad & tracking filters...
Patching...

Error: Current Blitz version caused patch comparison check to fail. Look for a new patcher release or create a new issue on Github!

    at Object.modifyFileAtLine (F:\snapshot\blitz-app-adblock\io.js)
    at start (F:\snapshot\blitz-app-adblock\blitz-app-adblock.js)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Press ENTER to quit...

**Comment by boyd-it** [comment]
Blitz version 1.14.17

**Comment by ByteDrummer** [comment]
I've made a pull request to fix this. Meanwhile, you may use my [fork](https://github.com/ByteDrummer/blitz-app-adblock). Just note that an error will pop up. Don't close it or it will stop blitz.

**Comment by lulzsun** [comment]
Merged pull requests and uploaded a new build. Thanks @ByteDrummer. Closing this issue.
