### ISSUE TITLE
Is there a way to stop blitz from popping up on front of all windows?

### ISSUE THREAD

**Issue by forest203** [lulzsun/blitz-app-adblock#6]
if u can point me in the right direction I could work on it.

**Comment by lulzsun** [comment]
Sorry for the super late reply, do you mean popping up during startup? Or during a game? 

I will be closing this as it is not really an issue, but more of a question. I will still response to replies.

**Comment by forest203** [comment]
After every game blitz will make it my active window. (also happens at the start of ARAM games.)

there is no setting that disables this feature. there is one setting that stops it from doing this in non-aram games but douse not stop the others.
