### ISSUE TITLE
Getting an error when patching

### ISSUE THREAD

**Issue by Cayk-rs** [lulzsun/blitz-app-adblock#66]
![image](https://user-images.githubusercontent.com/85299030/146674534-6b8edc51-7850-4bb6-aa72-9664bbf4b22e.png)

**Comment by lulzsun** [comment]
Heya, this project hasn't been working since #56. Even if the injection context is fixed, Blitz will still crash on a successful patch.

There hasn't been any progress on fixing this. Will be closing this issue.
