### ISSUE TITLE
Blitz Ad Block Error

### ISSUE THREAD

**Issue by ICrxzy** [lulzsun/blitz-app-adblock#67]
Upon running the program i get greeted with this message:
`Checking for Blitz...
win32
Extracting app.asar...
Downloading ad & tracking filters...
Patching...

Error: Current Blitz version doesn't contain the given injection context.
    at Object.modifyFileAfterContext (G:\snapshot\blitz-app-adblock\io.js)
    at start (G:\snapshot\blitz-app-adblock\blitz-app-adblock.js)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Press ENTER to quit...`

Any idea?

**Comment by lulzsun** [comment]
Hi, this has been mentioned before in other closed issues.

Even if this error was fixed, there is a bigger error that occurs after patching, see #56.

I don't think I have any plans on fixing this program any time soon, sorry.
