### ISSUE TITLE
This kind of an issue upon launching the adblock.exe

### ISSUE THREAD

**Issue by leevidavinci** [lulzsun/blitz-app-adblock#68]
![image](https://user-images.githubusercontent.com/98463786/151161935-a8ea20b4-713e-4f3d-9a70-354d9359857f.png)

**Comment by oliv1115** [comment]
Same issue for me.

**Comment by lulzsun** [comment]
Hey, this issue is the same as #66. 

As mentioned before, this patch no longer works properly even after the injection context is fixed, more details on this issue in #56.

There are no current plans (from me) to fix this. Maybe future contributors can figure out a solution.
