### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by Chilly167** [lulzsun/blitz-app-adblock#7]
I’m abit confused on how to install this ?

**Comment by lulzsun** [comment]
Hey,
You can download the latest release [here](https://github.com/lulzsun/blitz-app-adblock/releases). Extract it and run `blitz-app-adblock.exe`. At the time of this comment, it is still working on version 1.13.14, although some ads may get through the filter at this point.

**Comment by Chilly167** [comment]
Thankyou! for your extremely quick response
