### ISSUE TITLE
Current Blitz version doesn't contain the given injection context.

### ISSUE THREAD

**Issue by brian2k** [lulzsun/blitz-app-adblock#75]
`Checking for Blitz...
win32
Closing out Blitz...
Extracting app.asar...
Downloading ad & tracking filters...
Patching...

Error: Current Blitz version doesn't contain the given injection context.
    at Object.modifyFileAfterContext (G:\snapshot\blitz-app-adblock\io.js)
    at start (G:\snapshot\blitz-app-adblock\blitz-app-adblock.js)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Press ENTER to quit...`

This issue is not fixed nor is there any help here to get rid of this. Why am I getting this error and how to fix it?

**Comment by ThompsonNJ** [comment]
Same issue here

**Comment by xZinio** [comment]
Same

**Comment by lulzsun** [comment]
Hi, this project has not worked for almost a year now. If you look at the pinned issues, specifically #56, we have tried to look into a solution to that particular issue but failed. Interest in this repo has been dropped, and there are no plans (at least from me) to try to fix this. Thanks for understanding.
